### ISSUE TITLE
Could not find a declaration file for module 'vue-native-notification'.

### ISSUE THREAD

**Issue by onlysumitg** [dennisbruner/vue-native-notification#13]
I am trying to use vue-native-notification in a **NUXT project**. I just have basic knowledge on the js side.

 **https://nuxtjs.org/guide/plugins/#vue-plugins**

Code
`
import Vue from 'vue'

import VueNativeNotification from "vue-native-notification";

// const VueNativeNotification = require('vue-native-notification')

Vue.use(VueNativeNotification, {

  // Automatic permission request before

  // showing notification (default: true)

  requestOnNotify: true

})
`

Issue:
`module "c:/app_name/node_modules/vue-native-notification/index"
Could not find a declaration file for module 'vue-native-notification'. 'c:/app_name/node_modules/vue-native-notification/index.js' implicitly has an 'any' type.
  Try 'npm install @types/vue-native-notification' if it exists or add a new declaration (.d.ts) file containing 'declare module 'vue-native-notification';'ts(7016)`

Error:
`
SyntaxError
Unexpected token 'export'
`

I have tried 
`npm install @types/vue-native-notification`

But got the error
` Not Found - GET https://registry.npmjs.org/@types%2fvue-native-notification - Not found`

Please suggest.

**Comment by onlysumitg** [comment]
Never mind. It was nuxt issue.

**Comment by neuralsys** [comment]
How did you fixed it?
